### ISSUE TITLE
Always reports version 1.0.0.0

### ISSUE THREAD

**Issue by xapple** [cat-cfs/StandardImportToolPlugin#1]
I wanted to check if I had correctly put the new version in my PATH after installation and typed:

     $ StandardImportToolPlugin.exe --version

 And noticed all version always report:

     StandardImportToolPlugin 1.0.0.0

**Comment by smorken** [comment]
set version number for [this](https://github.com/cat-cfs/StandardImportToolPlugin/releases/tag/1.2.2.1) and future builds.  Thanks!
